[package]
name = "update-cli-programs"
version = "1.4.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
